"""unique session_id chunk_index on transcriptions

Revision ID: 0851d13684b8
Revises: 0726eb3362ee
Create Date: 2026-08-09 17:30:18.512139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0851d13684b8"
down_revision: Union[str, Sequence[str], None] = "0726eb3362ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_transcription_session_chunk",
        "transcriptions",
        ["session_id", "chunk_index"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_transcription_session_chunk", "transcriptions", type_="unique"
    )
    # ### end Alembic commands ###
