"""initial schema

Revision ID: 7b179e326c4f
Revises: 
Create Date: 2026-08-08 11:22:28.084498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b179e326c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_sessions_id'), 'translation_sessions', ['id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('asr_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['translation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptions_session_id'), 'transcriptions', ['session_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('mt_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_transcription_id'), 'translations', ['transcription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_transcription_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_transcriptions_session_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_translation_sessions_id'), table_name='translation_sessions')
    op.drop_table('translation_sessions')
    # ### end Alembic commands ###
